### ISSUE TITLE
Mapping characters to the string list

### ISSUE THREAD

**Issue by Debby4all** [ngozichukwuzoigwe-hub/darton-gamehub#2]
Append the user input to the guess list

**Comment by Ahuoyiza** [comment]
Your logic in the hangman game is good but can be improved.
So instead of appending user input to a list, and comparing the characters to the characters of the random word, you can just store your own words in a list, pick a random word from that list and compare each input to that word only without storing in a new list

Here is the link to my  repl file with sample code and comments so you can understand this particular flow
[Hangman_modified_on_replit](https://replit.com/@Ahuoyiza/hangman#main.dart).

I will close this issue now, if any other bugs show up you can push that branch make a pr and open an issue describing the bug, adds screenshots of error logs too
